// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// stand_tot
arma::mat stand_tot(arma::mat sitspe);
RcppExport SEXP weimea_stand_tot(SEXP sitspeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type sitspe(sitspeSEXP);
    __result = Rcpp::wrap(stand_tot(sitspe));
    return __result;
END_RCPP
}
// wm_rcpp
arma::mat wm_rcpp(arma::mat sitspe, arma::mat speatt);
RcppExport SEXP weimea_wm_rcpp(SEXP sitspeSEXP, SEXP speattSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type sitspe(sitspeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type speatt(speattSEXP);
    __result = Rcpp::wrap(wm_rcpp(sitspe, speatt));
    return __result;
END_RCPP
}
// count_if
int count_if(LogicalVector x);
RcppExport SEXP weimea_count_if(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    __result = Rcpp::wrap(count_if(x));
    return __result;
END_RCPP
}
// test_LR_cor
List test_LR_cor(arma::mat sitspe, arma::mat speatt, arma::mat env, CharacterVector cor_coef, double perm);
RcppExport SEXP weimea_test_LR_cor(SEXP sitspeSEXP, SEXP speattSEXP, SEXP envSEXP, SEXP cor_coefSEXP, SEXP permSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type sitspe(sitspeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type speatt(speattSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type env(envSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cor_coef(cor_coefSEXP);
    Rcpp::traits::input_parameter< double >::type perm(permSEXP);
    __result = Rcpp::wrap(test_LR_cor(sitspe, speatt, env, cor_coef, perm));
    return __result;
END_RCPP
}
// is_in
bool is_in(CharacterVector x, CharacterVector table);
RcppExport SEXP weimea_is_in(SEXP xSEXP, SEXP tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type table(tableSEXP);
    __result = Rcpp::wrap(is_in(x, table));
    return __result;
END_RCPP
}
// test_MR_cor
List test_MR_cor(arma::mat sitspe, arma::mat speatt, arma::mat env, CharacterVector test, CharacterVector cor_coef, double perm, double testLR_P, double testLR_perm);
RcppExport SEXP weimea_test_MR_cor(SEXP sitspeSEXP, SEXP speattSEXP, SEXP envSEXP, SEXP testSEXP, SEXP cor_coefSEXP, SEXP permSEXP, SEXP testLR_PSEXP, SEXP testLR_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type sitspe(sitspeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type speatt(speattSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type env(envSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type test(testSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cor_coef(cor_coefSEXP);
    Rcpp::traits::input_parameter< double >::type perm(permSEXP);
    Rcpp::traits::input_parameter< double >::type testLR_P(testLR_PSEXP);
    Rcpp::traits::input_parameter< double >::type testLR_perm(testLR_permSEXP);
    __result = Rcpp::wrap(test_MR_cor(sitspe, speatt, env, test, cor_coef, perm, testLR_P, testLR_perm));
    return __result;
END_RCPP
}
// fastLm_wm
List fastLm_wm(const arma::mat& X, const arma::colvec& y, bool intercept_included);
RcppExport SEXP weimea_fastLm_wm(SEXP XSEXP, SEXP ySEXP, SEXP intercept_includedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type intercept_included(intercept_includedSEXP);
    __result = Rcpp::wrap(fastLm_wm(X, y, intercept_included));
    return __result;
END_RCPP
}
// test_LR_lm
List test_LR_lm(arma::mat sitspe, arma::mat speatt, arma::mat env, double perm);
RcppExport SEXP weimea_test_LR_lm(SEXP sitspeSEXP, SEXP speattSEXP, SEXP envSEXP, SEXP permSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type sitspe(sitspeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type speatt(speattSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type env(envSEXP);
    Rcpp::traits::input_parameter< double >::type perm(permSEXP);
    __result = Rcpp::wrap(test_LR_lm(sitspe, speatt, env, perm));
    return __result;
END_RCPP
}
// keep_rows
arma::uvec keep_rows(arma::mat X);
RcppExport SEXP weimea_keep_rows(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    __result = Rcpp::wrap(keep_rows(X));
    return __result;
END_RCPP
}
// test_MR_lm
List test_MR_lm(arma::mat sitspe, arma::mat speatt, arma::mat env, CharacterVector test, const char* dependence, double perm, double testLR_P, double testLR_perm);
RcppExport SEXP weimea_test_MR_lm(SEXP sitspeSEXP, SEXP speattSEXP, SEXP envSEXP, SEXP testSEXP, SEXP dependenceSEXP, SEXP permSEXP, SEXP testLR_PSEXP, SEXP testLR_permSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type sitspe(sitspeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type speatt(speattSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type env(envSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type test(testSEXP);
    Rcpp::traits::input_parameter< const char* >::type dependence(dependenceSEXP);
    Rcpp::traits::input_parameter< double >::type perm(permSEXP);
    Rcpp::traits::input_parameter< double >::type testLR_P(testLR_PSEXP);
    Rcpp::traits::input_parameter< double >::type testLR_perm(testLR_permSEXP);
    __result = Rcpp::wrap(test_MR_lm(sitspe, speatt, env, test, dependence, perm, testLR_P, testLR_perm));
    return __result;
END_RCPP
}
