# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colSumsCpp <- function(X) {
    .Call('_weimea_colSumsCpp', PACKAGE = 'weimea', X)
}

rowSumsCpp <- function(X) {
    .Call('_weimea_rowSumsCpp', PACKAGE = 'weimea', X)
}

standCpp <- function(x) {
    .Call('_weimea_standCpp', PACKAGE = 'weimea', x)
}

wstandCpp <- function(x, w) {
    .Call('_weimea_wstandCpp', PACKAGE = 'weimea', x, w)
}

wmeanCpp <- function(x, w) {
    .Call('_weimea_wmeanCpp', PACKAGE = 'weimea', x, w)
}

wsdCpp <- function(x, w) {
    .Call('_weimea_wsdCpp', PACKAGE = 'weimea', x, w)
}

wcenterCpp <- function(x, w) {
    .Call('_weimea_wcenterCpp', PACKAGE = 'weimea', x, w)
}

corCpp <- function(x, y) {
    .Call('_weimea_corCpp', PACKAGE = 'weimea', x, y)
}

wcorCpp <- function(x, y, w) {
    .Call('_weimea_wcorCpp', PACKAGE = 'weimea', x, y, w)
}

cwmCpp <- function(L, t, wstand) {
    .Call('_weimea_cwmCpp', PACKAGE = 'weimea', L, t, wstand)
}

sncCpp <- function(L, e, wstand) {
    .Call('_weimea_sncCpp', PACKAGE = 'weimea', L, e, wstand)
}

sncCpp2 <- function(L, e) {
    .Call('_weimea_sncCpp2', PACKAGE = 'weimea', L, e)
}

ca_eig1_sqrt <- function(Y) {
    .Call('_weimea_ca_eig1_sqrt', PACKAGE = 'weimea', Y)
}

fourth <- function(e, L, t) {
    .Call('_weimea_fourth', PACKAGE = 'weimea', e, L, t)
}

stand_tot <- function(L) {
    .Call('_weimea_stand_tot', PACKAGE = 'weimea', L)
}

count_if <- function(x) {
    .Call('_weimea_count_if', PACKAGE = 'weimea', x)
}

submat_nonzero <- function(X, T) {
    .Call('_weimea_submat_nonzero', PACKAGE = 'weimea', X, T)
}

is_in <- function(x, table) {
    .Call('_weimea_is_in', PACKAGE = 'weimea', x, table)
}

complete_cases <- function(X) {
    .Call('_weimea_complete_cases', PACKAGE = 'weimea', X)
}

rm_missing_eLt <- function(e, L, t) {
    .Call('_weimea_rm_missing_eLt', PACKAGE = 'weimea', e, L, t)
}

test_cwm_cor <- function(e, L, t, test, perm, wcor, wstand) {
    .Call('_weimea_test_cwm_cor', PACKAGE = 'weimea', e, L, t, test, perm, wcor, wstand)
}

test_fourthCpp <- function(e, L, t, test, perm) {
    .Call('_weimea_test_fourthCpp', PACKAGE = 'weimea', e, L, t, test, perm)
}

fastLm_cwm <- function(X, y, stderr_incl) {
    .Call('_weimea_fastLm_cwm', PACKAGE = 'weimea', X, y, stderr_incl)
}

test_cwm_lm <- function(e, L, t, test, dependence, perm, wstand) {
    .Call('_weimea_test_cwm_lm', PACKAGE = 'weimea', e, L, t, test, dependence, perm, wstand)
}

lm_vectorfitCpp <- function(X, P) {
    .Call('_weimea_lm_vectorfitCpp', PACKAGE = 'weimea', X, P)
}

vectorfit_cwmCpp <- function(X, L, t, wstand, w, perm, test) {
    .Call('_weimea_vectorfit_cwmCpp', PACKAGE = 'weimea', X, L, t, wstand, w, perm, test)
}

