# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stand_tot <- function(sitspe) {
    .Call('weimea_stand_tot', PACKAGE = 'weimea', sitspe)
}

wm_rcpp <- function(sitspe, speatt) {
    .Call('weimea_wm_rcpp', PACKAGE = 'weimea', sitspe, speatt)
}

count_if <- function(x) {
    .Call('weimea_count_if', PACKAGE = 'weimea', x)
}

test_LR_cor <- function(sitspe, speatt, env, cor_coef, perm) {
    .Call('weimea_test_LR_cor', PACKAGE = 'weimea', sitspe, speatt, env, cor_coef, perm)
}

is_in <- function(x, table) {
    .Call('weimea_is_in', PACKAGE = 'weimea', x, table)
}

test_MR_cor <- function(sitspe, speatt, env, test, cor_coef, perm, testLR_P, testLR_perm) {
    .Call('weimea_test_MR_cor', PACKAGE = 'weimea', sitspe, speatt, env, test, cor_coef, perm, testLR_P, testLR_perm)
}

fastLm_wm <- function(X, y, intercept_included) {
    .Call('weimea_fastLm_wm', PACKAGE = 'weimea', X, y, intercept_included)
}

test_LR_lm <- function(sitspe, speatt, env, perm) {
    .Call('weimea_test_LR_lm', PACKAGE = 'weimea', sitspe, speatt, env, perm)
}

keep_rows <- function(X) {
    .Call('weimea_keep_rows', PACKAGE = 'weimea', X)
}

test_MR_lm <- function(sitspe, speatt, env, test, dependence, perm, testLR_P, testLR_perm) {
    .Call('weimea_test_MR_lm', PACKAGE = 'weimea', sitspe, speatt, env, test, dependence, perm, testLR_P, testLR_perm)
}

